=== rafael2k/presto/modules/dom/documentation/supported.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- DOM Level 2 -->
<!ENTITY % dom2 "dom2core | dom2events | dom2html | dom2style | dom2css | dom2travrange | dom2views">

<!-- DOM Level 3 (excluding stuff that hasn't changed from DOM Level 2) -->
<!ENTITY % dom3 "dom3core | dom3events | dom3loadsave | dom3xpath">

<!-- JavaScript Client 1.3 -->
<!ENTITY % js "js13">

<!-- What WG specifications -->
<!ENTITY % whatwg "webforms2 | webapps1">

<!-- Proprietary -->
<!ENTITY % proprietary "opera | operapf1 | msie | firefox">

<!-- Name of the item -->
<!ENTITY % name "name CDATA #REQUIRED">

<!-- Origin.  Inherited from parent if not specified. -->
<!ENTITY % origin "origin (various | %dom2; | %dom3; | %js; | %whatwg; | %proprietary;) #IMPLIED">
<!ENTITY % supported "supported (yes | no | optional) 'yes'">
<!ENTITY % common-attrs "%name; %origin; %supported;">

<!ENTITY % about "note | macro | feature | specification">
<!ENTITY % item "object | collection | method | constructor | property">

<!ENTITY % exception-types "DOMException | RangeException | XPathException | internal">

<!ELEMENT supported (class | %item;)*>
<!ATTLIST supported
  version CDATA #REQUIRED
  revision CDATA #REQUIRED>

<!ELEMENT interface ((%about;)*, (method | property)*)>
<!ATTLIST interface
  %common-attrs;>

<!ELEMENT object ((%about;)*, (interface | %item;)*)>
<!ATTLIST object
  %common-attrs;
  className CDATA #REQUIRED>

<!ELEMENT class ((%about;)*, (interface | %item;)*)>
<!ATTLIST class
  %common-attrs;
  className CDATA #REQUIRED
  baseClass CDATA #IMPLIED>

<!ELEMENT method ((%about;)*, exception*)>
<!ATTLIST method
  %common-attrs;
  primitiveType (string | long | unsignedLong | boolean) #IMPLIED
  classType CDATA #IMPLIED>

<!ELEMENT constructor ((%about;)*, exception*)>
<!ATTLIST constructor
  %common-attrs;
  className CDATA #IMPLIED
  constructedType CDATA #IMPLIED>

<!ELEMENT exception ((%about;)*)>
<!ATTLIST exception
  %common-attrs;
  type (%exception-types;) #REQUIRED
  on (read | write | call | construct) "call">

<!ELEMENT property ((%about;)*, exception*)>
<!ATTLIST property
  %common-attrs;
  primitiveType (string | long | unsignedLong | boolean) #IMPLIED
  classType CDATA #IMPLIED
  readOnly (silent | signalling | writable) "writable">

<!ELEMENT collection ((%about;)*)>
<!ATTLIST collection
  %origin;
  %supported;
  elementType CDATA #REQUIRED>

<!ELEMENT note (#PCDATA)>
<!ATTLIST note
  type (description | bug | limitation | extension) "description"
  %origin;
  %supported;>

<!ELEMENT macro (note*)>
<!ATTLIST macro
  name CDATA #REQUIRED
  defined (yes | no) "yes">

<!ELEMENT feature (note*)>
<!ATTLIST feature
  name CDATA #REQUIRED
  enabled (yes | no) "yes">

<!ELEMENT specification (note*)>
<!ATTLIST specification
  %origin;
  href CDATA #REQUIRED>

=== rafael2k/presto/modules/dom/documentation/supported.xml
<?xml version="1.0"?>

<!--

  Do you think this file is difficult to read and make sense of?
  Well, it is not supposed to be easy to read directly, it is supposed
  to be a comprehensive source of information about the DOM support in
  Opera.  Other means of making use of this file are or will be made
  available, such as XSLT stylesheets and script functions for
  loading, sorting, searching and presentation of the data herein.

-->

<!DOCTYPE supported SYSTEM "supported.dtd" [
  <!ENTITY plain-object "<note>Just a plain object with some constants.</note>">
  <!ENTITY req-dom2travrange "<feature name='FEATURE_DOM2_TRAV_AND_RANGE'/>">
  <!ENTITY req-dom2mutationevents "<feature name='FEATURE_DOM2_MUTATION_EVENTS'/>">
  <!ENTITY req-dom3core "<macro name='DOM3_CORE'/>">
  <!ENTITY req-dom3loadsave "<feature name='FEATURE_DOM3_LOAD_SAVE'/>">
  <!ENTITY req-dom3xpath "<feature name='FEATURE_DOM3_XPATH'/>">
  <!ENTITY req-dom3events "<macro name='DOM3_EVENTS'/>">
  <!ENTITY req-domhttp "<feature name='FEATURE_DOM_HTTP'/>">
  <!ENTITY req-domxslt "<macro name='DOM_XSLT_SUPPORT'/>">
  <!ENTITY req-webforms2 "<feature name='FEATURE_WEBFORMS2'/>">
  <!ENTITY req-userjs "<feature name='FEATURE_USER_JAVASCRIPT'/>">
  <!ENTITY req-remoteevents "<macro name='REMOTE_EVENTS_SUPPORT'/>">
  <!ENTITY req-ogp "<feature name='FEATURE_OGP'/>">
  <!ENTITY req-vxml "<feature name='FEATURE_VOICE'/>">
  <!ENTITY req-debug "<macro name='_DEBUG'/>">
  <!ENTITY req-asyncslotops "<feature name='FEATURE_ASYNC_SLOT_OPERATIONS'/>">
  <!ENTITY req-feeds "<macro name='WEBFEEDS_BACKEND_SUPPORT'/>">
 ]>

<?xml-stylesheet type="text/xml" href="supported.xslt"?>

<supported version="dumdum_2_beta_65" revision="$Id$">
  <object name="window" origin="various" className="Window">
    <note>The ECMAScript environment's global object.  All objects, properties
          and methods are also available as global variables.</note>

    <interface name="AbstractView" origin="dom2views">
      <specification origin="dom2views" href="http://www.w3.org/TR/DOM-Level-2-Views/views.html#Views-AbstractView"/>
      <property name="document" classType="Document"/>
    </interface>

    <interface name="EventTarget" origin="dom2events">
      <method name="dispatchEvent" supported="no"/>
      <method name="addEventListener"/>
      <method name="removeEventListener"/>
    </interface>

    <interface name="ViewCSS" origin="dom2css">
      <method name="getComputedStyle" classType="CSSStyleDeclaration"/>
    </interface>

    <property name="closed" primitiveType="boolean" origin="js13"><note type="limitation">Always false.</note></property>
    <property name="status" primitiveType="string" origin="js13"/>
    <property name="defaultStatus" primitiveType="string" origin="js13"/>
    <property name="event" classType="Event"><note>Returns the current event or null if there is no current event.</note></property>
    <property name="innerWidth" primitiveType="unsignedLong"/>
    <property name="innerHeight" primitiveType="unsignedLong"/>
    <property name="outerWidth" primitiveType="unsignedLong"/>
    <property name="outerHeight" primitiveType="unsignedLong"/>
    <property name="length" primitiveType="unsignedLong" origin="msie"><note>Returns window.frames.length.</note></property>
    <property name="name" primitiveType="string" origin="js13"/>
    <property name="opener" classType="Window" origin="js13"/>
    <property name="pageXOffset" primitiveType="unsignedLong"/>
    <property name="pageYOffset" primitiveType="unsignedLong"/>
    <property name="screenLeft" primitiveType="unsignedLong"/>
    <property name="screenTop" primitiveType="unsignedLong"/>
    <property name="screenX" primitiveType="unsignedLong"/>
    <property name="screenY" primitiveType="unsignedLong"/>
    <property name="window" classType="Window"><note>window.window == window</note></property>
    <property name="self" classType="Window"><note>window.self == window</note></property>
    <property name="parent" classType="Window"><note>Returns same window if there is no parent window.</note></property>
    <property name="top" classType="Window"/>
    <property name="frameElement" classType="Element"><note>Returns null if document is not in a frame or iframe.</note></property>

    <method name="alert" origin="js13"/>
    <method name="confirm" origin="js13"/>
    <method name="prompt" origin="js13"/>
    <method name="focus" origin="js13"/>
    <method name="blur" origin="js13"/>
    <method name="open" origin="js13"/>
    <method name="stop" origin="js13"/>
    <method name="print" origin="js13"/>
    <method name="setInterval" origin="js13"/>
    <method name="clearInterval" origin="js13"/>
    <method name="setTimeout" origin="js13"/>
    <method name="clearTimeout" origin="js13"/>
    <method name="home" origin="js13"/>
    <method name="moveTo" origin="js13"/>
    <method name="moveBy" origin="js13"/>
    <method name="resizeTo" origin="js13"/>
    <method name="resizeBy" origin="js13"/>
    <method name="scroll" origin="js13"/>
    <method name="scrollTo" origin="js13"/>
    <method name="scrollBy" origin="js13"/>
    <method name="back"/>
    <method name="forward"/>

    <method name="setDocument" origin="opera"/>

    <method name="addEventStream" origin="opera">&req-remoteevents;</method>
    <method name="removeEventStream" origin="opera">&req-remoteevents;</method>

    <!-- MSIE stuff -->
    <method name="attachEvent" origin="msie"/>
    <method name="detachEvent" origin="msie"/>
    <method name="navigate" origin="msie"/>

    <!-- Dummy functions -->
    <method name="captureEvents" origin="js13"><note type="limitation">Does nothing.</note></method>
    <method name="releaseEvents" origin="js13"><note type="limitation">Does nothing.</note></method>
    <method name="enableExternalCapture" origin="js13"><note type="limitation">Does nothing.</note></method>    <method name="disableExternalCapture" origin="js13"><note type="limitation">Does nothing.</note></method>

    <constructor name="Node" origin="dom2core" className="Node">
      <!-- Complete. -->

      <property name="ELEMENT_NODE" primitiveType="unsignedLong"/>
      <property name="ATTRIBUTE_NODE" primitiveType="unsignedLong"/>
      <property name="TEXT_NODE" primitiveType="unsignedLong"/>
      <property name="CDATA_SECTION_NODE" primitiveType="unsignedLong"/>
      <property name="ENTITY_REFERENCE_NODE" primitiveType="unsignedLong"><note type="limitation">Nodes of this type are not supported.</note></property>
      <property name="ENTITY_NODE" primitiveType="unsignedLong"/>
      <property name="PROCESSING_INSTRUCTION_NODE" primitiveType="unsignedLong"/>
      <property name="COMMENT_NODE" primitiveType="unsignedLong"/>
      <property name="DOCUMENT_NODE" primitiveType="unsignedLong"/>
      <property name="DOCUMENT_TYPE_NODE" primitiveType="unsignedLong"/>
      <property name="DOCUMENT_FRAGMENT_NODE" primitiveType="unsignedLong"/>
      <property name="NOTATION_NODE" primitiveType="unsignedLong"/>

      <property name="prototype" readOnly="silent"><note>Prototype object for Node class.</note></property>
      <exception type="DOMException" on="construct"><note type="limitation">Cannot be used to construct objects.</note></exception>
    </constructor>

    <constructor name="FeedEntry" origin="opera" className="FeedEntry">
      <!-- Complete. -->

      <property name="STATUS_UNREAD" primitiveType="unsignedLong"/>
      <property name="STATUS_READ" primitiveType="unsignedLong"/>
      <property name="STATUS_DELETED" primitiveType="unsignedLong"/>
    </constructor>

    <constructor name="Element" origin="dom2core" className="Element">
      <property name="prototype" readOnly="silent"><note>Prototype object for Element class.</note></property>
      <exception type="DOMException" on="construct"><note type="limitation">Cannot be used to construct objects.</note></exception>
    </constructor>

    <constructor name="Document" origin="dom2core" className="Document">
      <property name="prototype" readOnly="silent"><note>Prototype object for Document class.</note></property>
      <exception type="DOMException" on="construct"><note type="limitation">Cannot be used to construct objects.</note></exception>
    </constructor>

    <constructor name="DocumentFragment" origin="dom2core" className="DocumentFragment">
      <property name="prototype" readOnly="silent"><note>Prototype object for DocumentFragment class.</note></property>
      <exception type="DOMException" on="construct"><note type="limitation">Cannot be used to construct objects.</note></exception>
    </constructor>

    <constructor name="Attr" origin="dom2core" className="Attr">
      <property name="prototype" readOnly="silent"><note>Prototype object for Attr class.</note></property>
      <exception type="DOMException" on="construct"><note type="limitation">Cannot be used to construct objects.</note></exception>
    </constructor>

    <constructor name="Text" origin="dom2core" className="Text">
      <property name="prototype" readOnly="silent"><note>Prototype object for Text class.</note></property>
      <exception type="DOMException" on="construct"><note type="limitation">Cannot be used to construct objects.</note></exception>
    </constructor>

    <constructor name="Comment" origin="dom2core" className="Comment">
      <property name="prototype" readOnly="silent"><note>Prototype object for Comment class.</note></property>
      <exception type="DOMException" on="construct"><note type="limitation">Cannot be used to construct objects.</note></exception>
    </constructor>

    <constructor name="CDATASection" origin="dom2core" className="CDATASection">
      <property name="prototype" readOnly="silent"><note>Prototype object for CDATASection class.</note></property>
      <exception type="DOMException" on="construct"><note type="limitation">Cannot be used to construct objects.</note></exception>
    </constructor>
